config/routes.rb
Rails.application.routes.draw do
  resources :ws_logs
  require 'sidekiq/web'
  # require 'sidekiq/api'
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #mount Sidekiq::Web, at: '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ws_log.rb
class WsLog < ApplicationRecord

  def self.create_ws_log(params)
    #byebug
    @servicelog = WsLog.new(params)
    if @servicelog.save

      logger.info "Processing the request...Registro Agregado"
      puts("Registro Agregado-")
    else
      logger.info "Registro con problemas de inserción" + @servicelog.to_s
      puts("Registro con problemas de inserción" + @servicelog.to_s)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ws_logs_controller.rb
class WsLogsController < ApplicationController
  before_action :set_wslog, only: [:show, :edit, :update, :destroy]

  # GET /ws_logs
  # GET /ws_logs.json
  def index
    @wslogs = WsLog.all
  end

  # GET /ws_logs/1
  # GET /ws_logs/1.json
  def show
  end

  # GET /ws_logs/new
  def new
    @wslog = WsLog.new
  end

  # GET /ws_logs/1/edit
  def edit
  end

  # POST /ws_logs
  # POST /ws_logs.json
  def create
    @wslog = WsLog.new(wslog_params)

    respond_to do |format|
      if @wslog.save
        format.html { redirect_to @wslog, notice: 'Wslog was successfully created.' }
        format.json { render :show, status: :created, location: @wslog }
      else
        format.html { render :new }
        format.json { render json: @wslog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ws_logs/1
  # PATCH/PUT /ws_logs/1.json
  def update
    respond_to do |format|
      if @wslog.update(wslog_params)
        format.html { redirect_to @wslog, notice: 'Wslog was successfully updated.' }
        format.json { render :show, status: :ok, location: @wslog }
      else
        format.html { render :edit }
        format.json { render json: @wslog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ws_logs/1
  # DELETE /ws_logs/1.json
  def destroy
    @wslog.destroy
    respond_to do |format|
      format.html { redirect_to wslogs_url, notice: 'Wslog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wslog
      @wslog = WsLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wslog_params
      params.require(:wslog).permit(:params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ws_logs_helper.rb
module WsLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SisLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ws_logs/_form.html.erb
<%= form_with(model: wslog, local: true) do |form| %>
  <% if wslog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wslog.errors.count, "error") %> prohibited this wslog from being saved:</h2>

      <ul>
      <% wslog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :params %>
    <%= form.text_field :params, id: :wslog_params %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ws_logs/edit.html.erb
<h1>Editing Wslog</h1>

<%= render 'form', wslog: @wslog %>

<%= link_to 'Show', @wslog %> |
<%= link_to 'Back', ws_logs_path %>

app/views/ws_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wslogs</h1>

<table>
  <thead>
    <tr>
      <th>Params</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wslogs.each do |wslog| %>
      <tr>
        <td><%= wslog.params %></td>
        <td><%= link_to 'Show', wslog %></td>
        <td><%= link_to 'Edit', edit_ws_log_path(wslog) %></td>
        <td><%= link_to 'Destroy', wslog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wslog', new_ws_log_path %>

app/views/ws_logs/new.html.erb
<h1>New Wslog</h1>

<%= render 'form', wslog: @wslog %>

<%= link_to 'Back', ws_logs_path %>

app/views/ws_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Params:</strong>
  <%= @wslog.params %>
</p>

<%= link_to 'Edit', edit_ws_log_path(@wslog) %> |
<%= link_to 'Back', ws_logs_path %>